##
# GitHub Action to build GraalVM JRE Images
# Author: Arthur Lemeux Martelet
##

name: GraalVM - Java Runtime Environment - Docker Hub Publish

on:
  schedule:
    - cron: "0 0 * * 0"
  push:
    branches:
      - main

env:
  REGISTRY: docker.io
  IMAGE_NAME: arthlmx814/graalvm-jre

jobs:
  build-and-publish-graalvm-jre:
    name: Build and Publish GraalVM JRE Images

    runs-on: ubuntu-24.04

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      # https://github.com/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Get the latest GraalVM 21 Release from GitHub
      - name: Get GraalVM 21 Latest Release
        id: graalvm-21-latest-release
        run: |
          docker run --rm container-registry.oracle.com/graalvm/jdk:21 /bin/bash -c 'cat $JAVA_HOME/release' | grep "JAVA_VERSION=" | cut -d "=" -f 2 | tr -d '[:space:]' | tr -d '"' > /tmp/graalvm-21-latest-release
          echo "JAVA_RELEASE_VERSION=$(cat /tmp/graalvm-21-latest-release)" >> "$GITHUB_OUTPUT"

      # Get the latest GraalVM 24 Release from GitHub
      - name: Get GraalVM 24 Latest Release
        id: graalvm-24-latest-release
        run: |
          docker run --rm container-registry.oracle.com/graalvm/jdk:24 /bin/bash -c 'cat $JAVA_HOME/release' | grep "JAVA_VERSION=" | cut -d "=" -f 2 | tr -d '[:space:]' | tr -d '"' > /tmp/graalvm-24-latest-release
          echo "JAVA_RELEASE_VERSION=$(cat /tmp/graalvm-24-latest-release)" >> "$GITHUB_OUTPUT"

      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata for GraalVM 21 JRE Images (Ubuntu 22.04)
        id: docker-meta-graalvm-jre-21-jammy
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=false
            prefix=
            suffix=
          tags: |
            type=raw,enable=true,priority=100,prefix=,suffix=,value=21-jammy
            type=raw,enable=true,priority=200,prefix=,suffix=,value=${{ steps.graalvm-21-latest-release.outputs.JAVA_RELEASE_VERSION }}-jammy

      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata for GraalVM 21 JRE Images (Ubuntu 24.04)
        id: docker-meta-graalvm-jre-21-noble
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=false
            prefix=
            suffix=
          tags: |
            type=raw,enable=true,priority=100,prefix=,suffix=,value=21
            type=raw,enable=true,priority=200,prefix=,suffix=,value=${{ steps.graalvm-21-latest-release.outputs.JAVA_RELEASE_VERSION }}
            type=raw,enable=true,priority=100,prefix=,suffix=,value=21-noble
            type=raw,enable=true,priority=200,prefix=,suffix=,value=${{ steps.graalvm-21-latest-release.outputs.JAVA_RELEASE_VERSION }}-noble

      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata for GraalVM 24 JRE Images (Ubuntu 22.04)
        id: docker-meta-graalvm-jre-24-jammy
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=false
            prefix=
            suffix=
          tags: |
            type=raw,enable=true,priority=100,prefix=,suffix=,value=24-jammy
            type=raw,enable=true,priority=200,prefix=,suffix=,value=${{ steps.graalvm-24-latest-release.outputs.JAVA_RELEASE_VERSION }}-jammy

      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata for GraalVM 24 JRE Images (Ubuntu 24.04)
        id: docker-meta-graalvm-jre-24-noble
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=false
            prefix=
            suffix=
          tags: |
            type=raw,enable=true,priority=100,prefix=,suffix=,value=24
            type=raw,enable=true,priority=200,prefix=,suffix=,value=${{ steps.graalvm-24-latest-release.outputs.JAVA_RELEASE_VERSION }}
            type=raw,enable=true,priority=100,prefix=,suffix=,value=24-noble
            type=raw,enable=true,priority=200,prefix=,suffix=,value=${{ steps.graalvm-24-latest-release.outputs.JAVA_RELEASE_VERSION }}-noble

      # https://github.com/docker/build-push-action
      - name: Build and push GraalVM 21 JRE Images (Ubuntu 22.04)
        id: build-and-push-graalvm-jre-21-jammy
        uses: docker/build-push-action@v5
        with:
          context: ./21
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.docker-meta-graalvm-jre-21-jammy.outputs.tags }}
          labels: ${{ steps.docker-meta-graalvm-jre-21-jammy.outputs.labels }}
          build-args: |
            UBUNTU_VERSION=jammy
            JAVA_VERSION=${{ steps.graalvm-21-latest-release.outputs.JAVA_RELEASE_VERSION }}

      # https://github.com/docker/build-push-action
      - name: Build and push GraalVM 21 JRE Images (Ubuntu 24.04)
        id: build-and-push-graalvm-jre-21-noble
        uses: docker/build-push-action@v5
        with:
          context: ./21
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.docker-meta-graalvm-jre-21-noble.outputs.tags }}
          labels: ${{ steps.docker-meta-graalvm-jre-21-noble.outputs.labels }}
          build-args: |
            UBUNTU_VERSION=noble
            JAVA_VERSION=${{ steps.graalvm-21-latest-release.outputs.JAVA_RELEASE_VERSION }}

      # https://github.com/docker/build-push-action
      - name: Build and push GraalVM 24 JRE Images (Ubuntu 22.04)
        id: build-and-push-graalvm-jre-24-jammy
        uses: docker/build-push-action@v5
        with:
          context: ./24
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.docker-meta-graalvm-jre-24-jammy.outputs.tags }}
          labels: ${{ steps.docker-meta-graalvm-jre-24-jammy.outputs.labels }}
          build-args: |
            UBUNTU_VERSION=jammy
            JAVA_VERSION=${{ steps.graalvm-24-latest-release.outputs.JAVA_RELEASE_VERSION }}

      # https://github.com/docker/build-push-action
      - name: Build and push GraalVM 24 JRE Images (Ubuntu 24.04)
        id: build-and-push-graalvm-jre-24-noble
        uses: docker/build-push-action@v5
        with:
          context: ./24
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.docker-meta-graalvm-jre-24-noble.outputs.tags }}
          labels: ${{ steps.docker-meta-graalvm-jre-24-noble.outputs.labels }}
          build-args: |
            UBUNTU_VERSION=noble
            JAVA_VERSION=${{ steps.graalvm-24-latest-release.outputs.JAVA_RELEASE_VERSION }}
