##
# GitHub Action to build GraalVM JRE Images
# Author: Arthur Lemeux
##

name: GraalVM - Java Runtime Environment - Docker Hub Publish

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

env:
  REGISTRY: docker.io
  IMAGE_NAME: arthlmx814/graalvm-jre

jobs:
  build-and-publish-graalvm-jre-21:
    name: Build and Publish GraalVM JRE Images

    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      # https://github.com/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Get the latest GraalVM 17 Release from GitHub
      - name: Get GraalVM 17 Latest Release
        id: graalvm-17-latest-release
        run: |
          docker run --rm container-registry.oracle.com/graalvm/jdk:17 /bin/bash -c 'cat $JAVA_HOME/release' | grep "JAVA_VERSION=" | cut -d "=" -f 2 | tr -d '[:space:]' | tr -d '"' > /tmp/graalvm-17-latest-release
          echo "JAVA_RELEASE_VERSION=$(cat /tmp/graalvm-17-latest-release)" >> "$GITHUB_OUTPUT"

      # Get the latest GraalVM 21 Release from GitHub
      - name: Get GraalVM 21 Latest Release
        id: graalvm-21-latest-release
        run: |
          docker run --rm container-registry.oracle.com/graalvm/jdk:21 /bin/bash -c 'cat $JAVA_HOME/release' | grep "JAVA_VERSION=" | cut -d "=" -f 2 | tr -d '[:space:]' | tr -d '"' > /tmp/graalvm-21-latest-release
          echo "JAVA_RELEASE_VERSION=$(cat /tmp/graalvm-21-latest-release)" >> "$GITHUB_OUTPUT"

      # Get the latest GraalVM 22 Release from GitHub
      - name: Get GraalVM 22 Latest Release
        id: graalvm-22-latest-release
        run: |
          docker run --rm container-registry.oracle.com/graalvm/jdk:22 /bin/bash -c 'cat $JAVA_HOME/release' | grep "JAVA_VERSION=" | cut -d "=" -f 2 | tr -d '[:space:]' | tr -d '"' > /tmp/graalvm-22-latest-release
          echo "JAVA_RELEASE_VERSION=$(cat /tmp/graalvm-22-latest-release)" >> "$GITHUB_OUTPUT"

      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata for GraalVM 17 JRE Images
        id: docker-meta-graalvm-jre-17
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=false
            prefix=
            suffix=
          tags: |
            type=raw,enable=true,priority=100,prefix=,suffix=,value=17
            type=raw,enable=true,priority=200,prefix=,suffix=,value=${{ steps.graalvm-17-latest-release.outputs.JAVA_RELEASE_VERSION }}

      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata for GraalVM 21 JRE Images
        id: docker-meta-graalvm-jre-21
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=false
            prefix=
            suffix=
          tags: |
            type=raw,enable=true,priority=100,prefix=,suffix=,value=21
            type=raw,enable=true,priority=200,prefix=,suffix=,value=${{ steps.graalvm-21-latest-release.outputs.JAVA_RELEASE_VERSION }}

      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata for GraalVM 22 JRE Images
        id: docker-meta-graalvm-jre-22
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=false
            prefix=
            suffix=
          tags: |
            type=raw,enable=true,priority=100,prefix=,suffix=,value=22
            type=raw,enable=true,priority=200,prefix=,suffix=,value=${{ steps.graalvm-22-latest-release.outputs.JAVA_RELEASE_VERSION }}

      # https://github.com/docker/build-push-action
      - name: Build and push GraalVM 17 JRE Images
        id: build-and-push-graalvm-jre-17
        uses: docker/build-push-action@v5
        with:
          context: ./17
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.docker-meta-graalvm-jre-17.outputs.tags }}
          labels: ${{ steps.docker-meta-graalvm-jre-17.outputs.labels }}
          build-args: |
            JAVA_RELEASE_VERSION=${{ steps.graalvm-17-latest-release.outputs.JAVA_RELEASE_VERSION }}

      # https://github.com/docker/build-push-action
      - name: Build and push GraalVM 21 JRE Images
        id: build-and-push-graalvm-jre-21
        uses: docker/build-push-action@v5
        with:
          context: ./21
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.docker-meta-graalvm-jre-21.outputs.tags }}
          labels: ${{ steps.docker-meta-graalvm-jre-21.outputs.labels }}
          build-args: |
            JAVA_RELEASE_VERSION=${{ steps.graalvm-21-latest-release.outputs.JAVA_RELEASE_VERSION }}

      # https://github.com/docker/build-push-action
      - name: Build and push GraalVM 22 JRE Images
        id: build-and-push-graalvm-jre-22
        uses: docker/build-push-action@v5
        with:
          context: ./22
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.docker-meta-graalvm-jre-22.outputs.tags }}
          labels: ${{ steps.docker-meta-graalvm-jre-22.outputs.labels }}
          build-args: |
            JAVA_RELEASE_VERSION=${{ steps.graalvm-22-latest-release.outputs.JAVA_RELEASE_VERSION }}
